from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UsrAccess(QtWidgets.QMainWindow):
    def __init__(self) -> None:
        super(Ui_UsrAccess, self).__init__()
        self.setupUi(self)

    def setupUi(self, UsrAccess):
        UsrAccess.setObjectName("UsrAccess")
        UsrAccess.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../resource/img/tx3.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        UsrAccess.setWindowIcon(icon)
        UsrAccess.setStyleSheet("color: rgb(81, 2, 121);background-color: rgb(246, 242, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=UsrAccess)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(50, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox.setIconSize(QtCore.QSize(20, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(209, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(209, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_3.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_4.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.checkBox_5.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(246, 242, 255);\n"
"background-color: rgb(81, 2, 121);")
        self.pushButton_3.setObjectName("pushButton_3")
        UsrAccess.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=UsrAccess)
        self.statusbar.setObjectName("statusbar")
        UsrAccess.setStatusBar(self.statusbar)

        self.retranslateUi(UsrAccess)
        QtCore.QMetaObject.connectSlotsByName(UsrAccess)

    def retranslateUi(self, UsrAccess):
        _translate = QtCore.QCoreApplication.translate
        UsrAccess.setWindowTitle(_translate("UsrAccess", "管理员权限授权"))
        self.checkBox.setText(_translate("UsrAccess", "基本信息管理"))
        self.checkBox_2.setText(_translate("UsrAccess", "库存管理"))
        self.checkBox_3.setText(_translate("UsrAccess", "进货管理"))
        self.checkBox_4.setText(_translate("UsrAccess", "系统管理"))
        self.checkBox_5.setText(_translate("UsrAccess", "销售管理"))
        self.pushButton_3.setText(_translate("UsrAccess", "进入系统"))
